#!/usr/bin/env Rscript

# This script takes the JSON file generated by Pfam Scan and converts it into Jalview Features for the feature files
# written by Yasoo Morimoto on 26 may 2022

library(rjson)

file = list()

args = commandArgs(trailingOnly=T)
# test if there is at least one argument: if not, return an error
# TODO test if the file is a JSON
if (length(args)==0) {
  stop("At least one argument must be supplied (input file).json", call.=FALSE)
} else {
  file = fromJSON(file = args[1])
}

for (domain in c(1:length(file))) {
  Dname = file[[domain]][["name"]]
  SeqName = file[[domain]][["seq"]][["name"]]
  Dfrom = file[[domain]][["seq"]][["from"]]
  Dto = file[[domain]][["seq"]][["to"]]
  cat(c(Dname, SeqName,-1, Dfrom, Dto, Dname, 0.0), sep = "\t")
  cat("\n")
  
}

